language: node_js
node_js:
- node
before_script:
- npm install grunt-cli -g
env:
  global:
    secure: 1qAjXuJoTbP+theu7hu+eotbAbBUX4JecDKxwp1vBdiHB37HcTszqU7YfGkzOo++lqOyBRbLBRwaXz/6cs+Nd5aDUjl7fzRn7d0fj03OhIEOcfBICvVgss9QmMh5AdqL0n9w+qmlDD74PP2SEBtnSXosLijMkaPxfodyhdZwDfBrIJ5YbUjCviJLvrKxUB8ODeZYzxzI8mNvVFm1t2HtXwgBNuwBoyoc33v9aOUoC5fZAZPuLIYy3txrxIJylZv9DoqJLTCZZbz9yr7ey81DY6Mh1eiiovinvFFDDelchb1x/+jWmdfRfkzY3dMQ+te4pHz7I38nNW3S48o/Bowr222q2N6/0rvxTov+0VQFxz6izPgTml/ks4soZgwLKlt/pm5NegUkqz6oZvNEIAYoS4sXVwtCCSMRhbxrNyd3I5uxYtUdkupiLLIIdhQuzzSVuRjk9R8d4mu77TXvnS25+8cU0zX0KdzTMqghXHCck6gMY+FUNcLODL892LSStCNEJNWI1xxB65Zh/wu8kcCPE1d9yUMaZ0Btb6sjj3uBuCpPhlzsaCFJIzxIQs34E2682oVrn5c+byAjWp/j0MCPxpMzTxHEgnb3lbNsOq7sBJq2Nuy05kHEHrS4gobpPoDzlCYfBVUxLL3DNNtA4q6o/v7aHAasRqL4HM3U/rgDEmM=
